AllCops:
  TargetRubyVersion: 2.4
Rails:
  Enabled: true

inherit_gem:
  meowcop:
    - config/rubocop.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/rails'
    - 'bin/rake'
    - 'bin/spring'
    - 'bin/setup'
    - 'bin/update'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'config/environments/*'

Rails:
  Enabled: true

Rails/FindBy:
  Description: 'Prefer find_by over where.first.'
  Enabled: true

inherit_from: .rubocop_todo.yml

Style/TrailingUnderscoreVariable:
  Description: >-
                 Checks for the usage of unneeded trailing underscores at the
                 end of parallel variable assignment.
  AllowNamedUnderscoreVariables: true
  Enabled: false

# コメントをアスキー文字だけに限定しない (日本語OK)
Style/AsciiComments:
  Enabled: false

# String リテラルの表記をダブルクォートを許す (特別な理由が無い場合でもダブルクォートでOK)
Style/StringLiterals:
  Enabled: false

# 1_000_000 と区切り文字が 2 個以上必要になる場合のみ _ 区切りを必須にする
Style/NumericLiterals:
  MinDigits: 7

#==== Gry Generated ====

# EnforcedStyle: outdent => 14 offenses
# EnforcedStyle: indent => 0 offense
Layout/AccessModifierIndentation:
  EnforcedStyle: indent
  Enabled: true

# EnforcedStyle: leading => 0 offense
# EnforcedStyle: trailing => 23 offenses
Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true

# EnforcedStyle: empty_lines => 203 offenses
# EnforcedStyle: no_empty_lines => 2 offenses
Layout/EmptyLinesAroundBlockBody:
  EnforcedStyle: no_empty_lines
  Enabled: true

# EnforcedStyle: empty_lines => 177 offenses
# EnforcedStyle: empty_lines_except_namespace => 177 offenses
# EnforcedStyle: empty_lines_special => 130 offenses
# EnforcedStyle: no_empty_lines => 1 offense
# EnforcedStyle: beginning_only => 88 offenses
# EnforcedStyle: ending_only => 90 offenses
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines
  Enabled: true

# EnforcedStyle: aligned => 1 offense
# EnforcedStyle: indented => 22 offenses
# EnforcedStyle: indented_relative_to_receiver => 23 offenses
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
  Enabled: true

# EnforcedStyleInsidePipes: space => 68 offenses
# EnforcedStyleInsidePipes: no_space => 0 offense
Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space
  Enabled: true

# EnforcedStyle: space => 29 offenses
# EnforcedStyle: no_space => 0 offense
Layout/SpaceInsideStringInterpolation:
  EnforcedStyle: no_space
  Enabled: true

# EnforcedStyle: final_newline => 1 offense
# EnforcedStyle: final_blank_line => 125 offenses
Layout/TrailingBlankLines:
  EnforcedStyle: final_newline
  Enabled: true

# EnforcedStyle: snake_case => 0 offense
# EnforcedStyle: camelCase => 79 offenses
Naming/MethodName:
  EnforcedStyle: snake_case
  Enabled: true

# EnforcedStyle: snake_case => 0 offense
# EnforcedStyle: camelCase => 147 offenses
Naming/VariableName:
  EnforcedStyle: snake_case
  Enabled: true

# EnforcedStyle: when_needed => 125 offenses
# EnforcedStyle: always => 125 offenses
# EnforcedStyle: never => 0 offense
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
  Enabled: true

# EnforcedStyle: require_parentheses => 0 offense
# EnforcedStyle: require_no_parentheses => 29 offenses
# EnforcedStyle: require_no_parentheses_except_multiline => 29 offenses
Style/MethodDefParentheses:
  EnforcedStyle: require_parentheses
  Enabled: true

# EnforcedStyle: if => 17 offenses
# EnforcedStyle: case => 2 offenses
# EnforcedStyle: both => 19 offenses
Style/MissingElse:
  EnforcedStyle: case
  Enabled: true

# EnforcedStyle: implicit => 0 offense
# EnforcedStyle: explicit => 15 offenses
Style/RescueStandardError:
  EnforcedStyle: implicit
  Enabled: true

# EnforcedStyle: return => 0 offense
# EnforcedStyle: return_nil => 10 offenses
Style/ReturnNil:
  EnforcedStyle: return
  Enabled: true

# EnforcedStyle: percent => 25 offenses
# EnforcedStyle: brackets => 2 offenses
Style/SymbolArray:
  EnforcedStyle: percent
  Enabled: true

Metrics/AbcSize:
  Enabled: true
  Max: 33.0

Metrics/ClassLength:
  Enabled: true
  Max: 150

Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 7

# 以下の理由で120文字に制限
# * GitHubのUnified Diffで横スクロールが発生しない文字数
# * ワイドディスプレイで、左右分割したときに、折り返し発生しなさそうな上限
Metrics/LineLength:
  Enabled: true
  Max: 120
  Exclude:
    - "config/routes.rb"
    - "config/routes/*.rb"
    - "db/migrate/*.rb"
    - "spec/**/*.rb"
    - "Gemfile"

Metrics/MethodLength:
  Enabled: true
  Max: 20
  Exclude:
    - "config/routes.rb"
    - "config/routes/*.rb"
    - "db/migrate/*.rb"
    - "spec/**/*.rb"

Metrics/BlockLength:
  Enabled: true
  Max: 27
  Exclude:
    - "config/routes.rb"
    - "config/routes/*.rb"
    - "db/migrate/*.rb"
    - "spec/**/*.rb"

Metrics/ModuleLength:
  Enabled: true
  Max: 100

Metrics/ParameterLists:
  Enabled: true
  Max: 8

Metrics/PerceivedComplexity:
  Enabled: true
  Max: 7

# EnforcedStyle: action => 0 offense
# EnforcedStyle: filter => 22 offenses
Rails/ActionFilter:
  EnforcedStyle: action
  Enabled: true

Rails/NotNullColumn:
  Enabled: false
